import { Comfortaa } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layouts/Navbar";

const comfortaa = Comfortaa({
  weight: ["300", "400", "500", "600", "700"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={comfortaa.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
