export const backendData = {
  insights: [
    "Videos receive an average of 7,765 likes, suggesting strong audience appeal.",
    "The average number of comments on videos is 587, indicating moderate discussion.",
    "Videos generate an average of 136 shares per post, showcasing decent virality.",
    "Compared to static images, videos achieve significantly higher engagement.",
    "Videos' average engagement rate is higher than static images but lower than reels.",
    "The most liked video received 9630 likes, highlighting potential for high engagement.",
    "Videos with captivating descriptions tend to receive more comments and shares.",
    "Using relevant hashtags can boost video visibility and engagement.",
    "Videos show a slightly lower share rate compared to reels, suggesting room for improvement.",
    "The average engagement for videos is competitive with carousels.",
  ],
  statistics: {
    reels: {
      average_likes: 8824,
      average_comments: 696,
      average_shares: 292,
      average_engagement: 38,
    },
    videos: {
      average_likes: 7765,
      average_comments: 587,
      average_shares: 136,
      average_engagement: 34,
    },
    static_images: {
      average_likes: 3135,
      average_comments: 172,
      average_shares: 54,
      average_engagement: 22,
    },
    carousels: {
      average_likes: 5023,
      average_comments: 406,
      average_shares: 160,
      average_engagement: 30,
    },
  },
  top_hashtags: {
    reels: [
      "#reels",
      "#viral",
      "#trending",
      "#lifeisbetterinmotion",
      "#quickmoments",
    ],
    videos: [
      "#videocontent",
      "#watchtilltheend",
      "#pressplay",
      "#videomarketing",
      "#storytelling",
    ],
    static_images: [
      "#photography",
      "#photooftheday",
      "#stillness",
      "#beauty",
      "#inspiration",
    ],
    carousels: [
      "#carouselpost",
      "#swipeup",
      "#explore",
      "#multipleslides",
      "#discovermore",
    ],
  },
};
